### ISSUE TITLE
Help with restoring Play Store purchase

### ISSUE THREAD

**Issue by zubayrrr** [oceanbit/GitShark#106]
Hello, thank you for this amazing app.
I had downloaded(paid) the app from the play store. I am migrating to a different phone, I signed in (on Play Store) using the account I had purchased the app with. How do I restore my purchase?

I apologise about the duplicate issues, I clicked on the button multiple times as I thought it was unresponsive and that lead to it creating a bunch of these issues.

Thanks in advance.

**Comment by crutchcorn** [comment]
@zubayrrr Please fill in the template for the issue so that I can properly assist
