### ISSUE TITLE
Add partial git merge support

### ISSUE THREAD

**Issue by crutchcorn** [oceanbit/GitShark#20]
In `isomorphic-git` (the baseline to our Git functionality), if you attempt to introduce a merge that will cause a merge conflict, [it will not succeed and throw a `mergenotsupportedError`](https://isomorphic-git.org/docs/en/merge.html#limitations).

**Comment by crutchcorn** [comment]
For tracking's sake - The request for a GH issue related to this:

https://github.com/isomorphic-git/isomorphic-git/issues/16#issuecomment-646893884

**Comment by thelinuxlich** [comment]
+1

**Comment by crutchcorn** [comment]
Closing this in favor of #95, as we're no longer limited by `isomorphic-git` in this regard. Eventual initial implementation of git merge will include merge conflicts OOTB
